id: IC3E2A0C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T13:24:09+00:00'
last_modified: '2022-06-09T17:46:12.608199+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27487
  title: མན་ངག་གནད་ཀྱི་རྫོང་འཕྲང་གི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B644:
      image_group_id: I4500
      title: ''
      total_pages: 614
      order: 1
      base_file: B644.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
